DEF DEBUG        EQU 1
DEF SKIP_JUNK    EQU 1
DEF LABEL_JUNK   EQU 0
DEF OPTIMIZE     EQU 1
DEF FIX_BUGS     EQU 1
DEF FIX_FUN_BUGS EQU 1
DEF IMPROVE      EQU 1
DEF TEST         EQU 1
DEF HEADER_TEST  EQU 0
INCLUDE "main.asm"