DEF DEBUG        EQU 0
DEF SKIP_JUNK    EQU 1
DEF LABEL_JUNK   EQU 0
DEF OPTIMIZE     EQU 0
DEF FIX_BUGS     EQU 0
DEF FIX_FUN_BUGS EQU 0
DEF IMPROVE      EQU 0
DEF TEST         EQU 0
DEF HEADER_TEST  EQU 0
INCLUDE "main.asm"